import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{Plus,ChevronLeft,ChevronRight,Layers3,Check,Trash2}from'lucide-react';import{addDays,addWeeks,format,startOfWeek}from'date-fns';import'./style.css';
type Task={id:string,title:string,subtitle?:string,due?:string,ongoing?:boolean,done?:boolean};
const seed:Task[]=[
{id:'1',title:'ENES210',subtitle:'Quiz 1',due:'2026-09-14T23:59'},
{id:'2',title:'CMSC330',subtitle:'Lecture Quiz',due:'2026-09-14T23:59'},
{id:'3',title:'Tennis',subtitle:'RecWell Shift',due:'2026-09-16T16:00'},
{id:'4',title:'MATH241',subtitle:'Quiz (in class)',due:'2026-09-17T12:00'},
{id:'5',title:'STAT410',subtitle:'Quiz (in class)',due:'2026-09-17T12:00'},
{id:'6',title:'STAT410',subtitle:'HW',due:'2026-09-17T23:59'},
{id:'7',title:'ENES210',subtitle:'Quiz 2',due:'2026-09-20T23:59'},
{id:'8',title:'ENES210',subtitle:'Weekly Activity 1',due:'2026-09-20T23:59'},
{id:'9',title:'CMSC351',subtitle:'HW',due:'2026-09-22T11:00'},
{id:'10',title:'CMSC330',subtitle:'Project 0 + Project 1',ongoing:true}];
const colors=['blue','violet','cyan','pink','green'];
function App(){const[tasks,setTasks]=useState<Task[]>(()=>{try{return JSON.parse(localStorage.getItem('tasks')||'null')||seed}catch{return seed}});const[week,setWeek]=useState(new Date(2026,8,14));const[modal,setModal]=useState<Date|null>(null);const[title,setTitle]=useState('');const[sub,setSub]=useState('');const[time,setTime]=useState('23:59');useEffect(()=>localStorage.setItem('tasks',JSON.stringify(tasks)),[tasks]);const start=useMemo(()=>startOfWeek(week,{weekStartsOn:1}),[week]);const days=Array.from({length:7},(_,i)=>addDays(start,i));const add=()=>{if(!title.trim())return;const d=modal!;setTasks(x=>[...x,{id:crypto.randomUUID(),title:title.trim(),subtitle:sub.trim(),due:`${format(d,'yyyy-MM-dd')}T${time}`}]);setModal(null);setTitle('');setSub('')};const toggle=(id:string)=>setTasks(t=>t.map(x=>x.id===id?{...x,done:!x.done}:x));const del=(id:string)=>setTasks(t=>t.filter(x=>x.id!==id));return <main><header><div><h1>{format(start,'MMMM yyyy')}</h1><p>WEEK OF {format(start,'MMM d').toUpperCase()} – {format(addDays(start,6),'MMM d').toUpperCase()}</p></div><div className="nav"><button onClick={()=>setWeek(addWeeks(week,-1))}><ChevronLeft/></button><span>{format(start,'MMM yyyy').toUpperCase()}</span><button onClick={()=>setWeek(addWeeks(week,1))}><ChevronRight/></button></div></header><section className="week">{days.map((d,i)=><article className="day" key={i}><div className="dayhead"><span>{format(d,'EEE').toUpperCase()}</span><b>{format(d,'d')}</b></div><div className="tasklist">{tasks.filter(t=>t.due&&format(new Date(t.due),'yyyy-MM-dd')===format(d,'yyyy-MM-dd')).map((t,j)=><TaskCard key={t.id} task={t} color={colors[j%colors.length]} toggle={toggle} del={del}/>)}</div><button className="add" onClick={()=>setModal(d)}><Plus/></button></article>)}</section><section className="ongoing"><h3><Layers3/> ONGOING / NO DUE DATE</h3><div className="ongoingGrid">{tasks.filter(t=>t.ongoing).map(t=><TaskCard key={t.id} task={t} color="violet" toggle={toggle} del={del}/>)}</div></section>{modal&&<div className="shade" onMouseDown={()=>setModal(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><h2>Add task</h2><input autoFocus placeholder="Course / task" value={title} onChange={e=>setTitle(e.target.value)}/><input placeholder="Description" value={sub} onChange={e=>setSub(e.target.value)}/><label>Due time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><div className="actions"><button onClick={()=>setModal(null)}>Cancel</button><button className="primary" onClick={add}>Add task</button></div></div></div>}</main>}
function TaskCard({task,color,toggle,del}:{task:Task,color:string,toggle:(x:string)=>void,del:(x:string)=>void}){const overdue=!!task.due&&!task.done&&new Date(task.due)<new Date();return <div className={`task ${overdue?'overdue ':''}${task.done?'done ':''}${color}`}><i/><div className="copy"><strong>{task.title}</strong>{task.subtitle&&<span>{task.subtitle}</span>}{task.due&&<small>{overdue?'OVERDUE • ':''}{format(new Date(task.due),'h:mm a')}</small>}{task.ongoing&&<small>Work on whenever</small>}</div><div className="tools"><button onClick={()=>toggle(task.id)} title="Complete"><Check/></button><button onClick={()=>del(task.id)} title="Delete"><Trash2/></button></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
